- Paco-iOS/Paco/config/Paco-Info.plist
- Paco-iOS/Paco/source/core/authentication/PacoAuthenticator.m
- Paco-iOS/Paco/source/core/client/PacoClient.h
These are two commits for release 1.1.4.
> ios release 1.1.4

- Paco-Server/ear/default/web/js/controllers.js
- Paco-Server/ear/default/web/js/directives.js
- Paco-Server/ear/default/web/partials/data.html
Using more elaborate CSV parsing to resolve this issue. I ran out of quota (error 503) on pacostage so I'm having trouble testing this now.
> Fixes csv parsing issue #1006

- Paco/src/com/pacoapp/paco/triggering/NotificationCreator.java
Modified code to allow for larger notification messages. The default notification style has been changed to bigStyle
> Notification change from default layout to extended layout

- Paco/assets/js_api_V2/paco_core.js
- Paco/assets/js_api_V2/paco_render.js
- Paco/assets/js_api_V2/paco_util.js
Added a file paco_core to the new javascript library v2
> New JS API v2 - Paco Core

- Paco-Server/ear/default/web/css/groups.css
- Paco-Server/ear/default/web/css/style.css
- Paco-Server/ear/default/web/js/controllers.js
- Paco-Server/ear/default/web/js/services.js
- Paco-Server/ear/default/web/partials/advanced.html
- Paco-Server/ear/default/web/partials/basics.html
Cleans up some of the ace callbacks. Adds default instruction text to the appropriate experiment template field that includes some return breaks for better readability.
> Adds source editor for postInstallInstructions to fix #1070

- Paco-Server/ear/default/web/css/list.css
- Paco-Server/ear/default/web/partials/list.html
This is probably a misuse of tabs (kind of like the editor tabs) but it's a working solution we can iterate on in future designs. I think it might work well if the tab bar goes all the way across the screen, just below the toolbar, and they doc to the top when scrolled down.
> Adds rudimentary tabs to the list view to fix #1180

- Paco/src/com/pacoapp/paco/triggering/NotificationCreator.java
- Shared/src/com/pacoapp/paco/shared/model2/PacoNotificationAction.java
Worked on #1234 - added functionality for the Notification LED color - Android.
> Added functionality for custom Android Notification LED color (No UI)

- Paco/src/com/pacoapp/paco/triggering/NotificationCreator.java
- Paco/src/com/pacoapp/paco/ui/ExperimentExecutor.java
- Paco/src/com/pacoapp/paco/ui/ExperimentExecutorCustomRendering.java
- Shared/src/com/pacoapp/paco/shared/model2/PacoNotificationAction.java
Implemented non-dismissible notifications ( #1235 ) - Looks like the notifications are already being cancelled when the user saves the survey.
> Android: Added support for non-dismissible notifications.

- Paco-Server/ear/default/web/partials/admin.html
This should show the mobile shareable link in Edit->Admin tab.
Implements #1269
> Server: Shows pacoapp://experiment/123456 link in Edit-Admin tab

- Paco-Server/ear/default/web/css/groups.css
- Paco-Server/ear/default/web/css/style.css
- Paco-Server/ear/default/web/js/controllers.js
- Paco-Server/ear/default/web/js/directives.js
- Paco-Server/ear/default/web/partials/action.html
- Paco-Server/ear/default/web/partials/advanced.html
- Paco-Server/ear/default/web/partials/groups.html
- Paco-Server/ear/default/web/partials/trigger.html
> Switches no-ios away from md-tooltip and fixes #1332

- Paco-Server/ear/default/web/partials/admin.html
I added Marios' mobile link but moved it over to the right column, below the fold.
> Pacoapplink

- Paco-Server/ear/default/web/css/data.css
- Paco-Server/ear/default/web/css/style.css
- Paco-Server/ear/default/web/js/controllers.js
- Paco-Server/ear/default/web/partials/data.html
> Web issues

- Paco-Server/ear/default/web/js/services.js
- Paco/AndroidManifest.xml
- Paco/src/com/pacoapp/paco/sensors/android/BroadcastTriggerReceiver.java
- PacoTest/src/com/google/android/apps/paco/test/BroadcastTriggerReceiverTest.java
- Shared/src/com/pacoapp/paco/shared/model2/InterruptCue.java
Adding a trigger for the event of a new app installation.
> Add packageinstall trigger

- Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java
This pull request fixes a race condition when performing concurrent read/writes on Paco's DB (fixes #1458 )
> Fix for #1458

- Paco/src/com/pacoapp/paco/js/bridge/JavascriptPackageManager.java
- Paco/src/com/pacoapp/paco/sensors/android/AndroidInstalledApplications.java
- Paco/src/com/pacoapp/paco/sensors/android/BroadcastTriggerReceiver.java
- Paco/src/com/pacoapp/paco/sensors/android/BroadcastTriggerService.java
- Paco/src/com/pacoapp/paco/sensors/android/RuntimePermissionMonitorService.java
- Paco/src/com/pacoapp/paco/ui/InformedConsentActivity.java
- Shared/src/com/pacoapp/paco/shared/util/ExperimentHelper.java
- Shared/src_non_j2objc/com/pacoapp/paco/shared/model2/JsonConverter.java
Also allow triggers to listen for all possible filters by adding a wildcard ("*") filter.
> Pass on app installation / removal info to listening triggers

- Paco-Server/ear/default/web/css/basics.css
- Paco-Server/ear/default/web/js/controllers.js
- Paco-Server/ear/default/web/partials/action.html
- Paco-Server/ear/default/web/partials/admin.html
- Paco-Server/ear/default/web/partials/advanced.html
- Paco-Server/ear/default/web/partials/basics.html
- Paco-Server/ear/default/web/partials/input.html
- Paco-Server/ear/default/web/partials/list.html
- Paco-Server/ear/default/web/partials/schedule.html
- Paco-Server/ear/default/web/partials/trigger.html
I had some time and thought I'd work on a few of the old, outstanding web bugs. Unfortunately, I'm having trouble with pacostage instances in the new Cloud console and will have to investigate that further.
> Web fixes small

- Paco/assets/custom_base.js
- Paco/assets/custom_base_interpreter.js
- Paco/src/com/pacoapp/paco/js/bridge/JavascriptEventLoader.java
- Paco/src/com/pacoapp/paco/js/bridge/JsUtil.java
- Paco/src/com/pacoapp/paco/js/bridge/SQLQuery.java
- Paco/src/com/pacoapp/paco/model/DatabaseHelper.java
- Paco/src/com/pacoapp/paco/model/ExperimentProvider.java
- Paco/src/com/pacoapp/paco/model/ExperimentProviderUtil.java
- Paco/src/com/pacoapp/paco/model/ExperimentUtil.java
- PacoTest/tests/com/google/android/apps/paco/ExperimentUtilTestCase.java
- PacoTest/tests/com/pacoapp/paco/js/bridge/JsUtilTest.java
I see quite a few formatting issues (like indentations, spaces, line breaks...). I will fix those and check it in ASAP. Let me know your feedback on the feature implementation.
> Get by query

- Paco-Server/ear/migration/WEB-INF/web.xml
- Paco-Server/src/com/google/sampling/experiential/datastore/FailedEventServerColumns.java
- Paco-Server/src/com/google/sampling/experiential/server/CloudSQLDao.java
- Paco-Server/src/com/google/sampling/experiential/server/CloudSQLDaoImpl.java
- Paco-Server/src/com/google/sampling/experiential/server/CloudSqlSearchServlet.java
- Paco-Server/src/com/google/sampling/experiential/server/FailedEventsInsertServlet.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/CloudSQLMigrationDaoImpl.java
- Shared/src/com/pacoapp/paco/shared/util/Constants.java
Ignore my earlier pull request
> Failed event processing, streaming bug, join status in event tables fix

- Paco-Server/src/com/google/sampling/experiential/datastore/CatchupFailureServerColumns.java
- Paco-Server/src/com/google/sampling/experiential/model/Event.java
- Paco-Server/src/com/google/sampling/experiential/server/CloudSQLDao.java
- Paco-Server/src/com/google/sampling/experiential/server/CloudSQLDaoImpl.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/CloudSQLCreateServlet.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/CloudSQLMigrationDao.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/CloudSQLMigrationDaoImpl.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/MigrationBackendServlet.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/MigrationDataRetriever.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/MigrationFrontendServlet.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/MigrationJob.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/MigrationLookupTable.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/jobs/CSInsertEventsJob.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/jobs/CatchUpDateRangeJob.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/jobs/EventStatsCounterMigrationJob.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/jobs/ExperimentHubMigrationJob.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/jobs/ExperimentJDOToDatastoreMigration.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/jobs/ExperimentTitleLowercaseMigrationJob.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/jobs/FeedbackTypeRepairMigration.java
- Paco-Server/src/com/google/sampling/experiential/server/stats/usage/UsageStatsBackfillJob.java
- Paco-Server/src/com/google/sampling/experiential/shared/TimeUtil.java
> Catchup job process

- Paco-Server/ear/default/WEB-INF/appengine-web.xml
- Paco-Server/ear/default/web/css/style.css
- Paco-Server/ear/default/web/partials/input.html
- Paco-Server/ear/mapreduce/WEB-INF/appengine-web.xml
- Paco-Server/ear/migration/WEB-INF/appengine-web.xml
- Paco-Server/ear/reportworker/WEB-INF/appengine-web.xml
Masks app engine credentials and fixes issue #1512
> Bugfix #1512

- Paco-Server/src/com/google/sampling/experiential/server/CloudSQLConnectionManager.java
- Paco-Server/src/com/google/sampling/experiential/server/CloudSQLDao.java
- Paco-Server/src/com/google/sampling/experiential/server/CloudSQLDaoImpl.java
- Paco-Server/src/com/google/sampling/experiential/server/EventRetriever.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/MigrationDataRetriever.java
- Paco-Server/src/com/google/sampling/experiential/server/migration/jobs/TestJDODSCompat.java
Connection leak fixed, with connection config changes.
> Catchup fixes

- Paco-Server/ear/default/web/css/groups.css
- Paco-Server/ear/default/web/css/style.css
- Paco-Server/ear/default/web/partials/advanced.html
Fixes issue #1547 : Displays iOS incompatibility icon when advanced options other than 'Static Message' is chosen.
> Fixes issue #1547

- Paco-Server/ear/default/web/css/basics.css
- Paco-Server/ear/default/web/partials/basics.html
> Fixes issue #1328

- Paco-Server/ear/default/web/css/vizStyles.css
- Paco-Server/ear/default/web/data/events.json
- Paco-Server/ear/default/web/data/experiments.json
- Paco-Server/ear/default/web/visualizations/vizApp.js
- Paco-Server/ear/default/web/visualizations/vizController.js
- Paco-Server/ear/default/web/visualizations/vizDataFactory.js
- Paco-Server/ear/default/web/visualizations/vizDirective.js
- Paco-Server/ear/default/web/viz.html
Create viz controller to access data from the viz data factory service (which contains factory methods to access data from static files - experiments.json and events.json). Viz controller enables to render the viz using custom directives.
> Stand alone simple visualization

- Paco-Server/ear/default/web/css/viz/vizStyles.css
- Paco-Server/ear/default/web/index.html
- Paco-Server/ear/default/web/js/app.js
- Paco-Server/ear/default/web/js/viz/vizController.js
- Paco-Server/ear/default/web/js/viz/vizDirective.js
- Paco-Server/ear/default/web/js/viz/vizService.js
- Paco-Server/ear/default/web/partials/experiment.html
- Paco-Server/ear/default/web/partials/list.html
- Paco-Server/ear/default/web/partials/viz/viz.html
Edit viz controller, directive, data service and HTML to integrate Paco App's data from experiments.json and events.json.
> Simple Viz integrated with Paco App

- Paco-Server/src/com/google/sampling/experiential/server/CloudSQLDao.java
- Paco-Server/src/com/google/sampling/experiential/server/CloudSQLDaoImpl.java
- Paco-Server/src/com/google/sampling/experiential/server/CloudSqlSearchServlet.java
- Shared/src/com/pacoapp/paco/shared/util/ErrorMessages.java
- Shared/src/com/pacoapp/paco/shared/util/QueryJsonParser.java
- Shared/src/com/pacoapp/paco/shared/util/QueryPreprocessor.java
ISO date format in projection queries fixed, made the json request nodes to be case insensitve
> Case insensitivity in Json request node names and iso date format

- Paco-Server/ear/default/web/css/viz/vizStyles.css
- Paco-Server/ear/default/web/index.html
- Paco-Server/ear/default/web/js/controllers.js
- Paco-Server/ear/default/web/js/experiment.json
- Paco-Server/ear/default/web/js/viz/vizController.js
- Paco-Server/ear/default/web/js/viz/vizDirective.js
- Paco-Server/ear/default/web/js/viz/vizService.js
- Paco-Server/ear/default/web/partials/experiment.html
- Paco-Server/ear/default/web/partials/list.html
- Paco-Server/ear/default/web/partials/viz/dateTimeControl.html
- Paco-Server/ear/default/web/partials/viz/inputsControl.html
- Paco-Server/ear/default/web/partials/viz/participantsControl.html
- Paco-Server/ear/default/web/partials/viz/viz.html
- Paco-Server/tests/com/google/sampling/experiential/datastore/JsonConverterTest.java
- Shared/src/com/pacoapp/paco/shared/model2/ExperimentDAO.java
- Shared/src/com/pacoapp/paco/shared/model2/Visualizations.java
> Save visualizations
